#!/usr/bin/env python3
"""Build Mihomo classical Rule Providers from maintained local rule sources."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    "LAN": "direct/LAN.list",
    "China": "direct/China.list",
    "Finance": "direct/Finance.list",
    "Payment": "direct/Payment.list",
    "Apple": "direct/Apple.list",
    "Microsoft": "direct/Microsoft.list",
    "OpenAI": "ai/OpenAI.list",
    "Claude": "ai/Claude.list",
    "GoogleAI": "ai/GoogleAI.list",
    "AI-Platform": "ai/AI-Platform.list",
    "AI-Image": "ai/AI-Image.list",
    "AI-Model": "ai/AI-Model.list",
    "GitHub": "developer/GitHub.list",
    "Copilot": "developer/Copilot.list",
    "Developer": "developer/Developer.list",
    "Google": "media/Google.list",
    "YouTube": "media/YouTube.list",
    "Netflix": "media/Netflix.list",
    "DisneyPlus": "media/DisneyPlus.list",
    "Spotify": "media/Spotify.list",
    "Twitch": "media/Twitch.list",
    "Japan-Media": "media/Japan-Media.list",
    "Telegram": "social/Telegram.list",
    "X": "social/X.list",
    "Instagram": "social/Instagram.list",
    "Facebook": "social/Facebook.list",
    "Advertising": "security/Advertising.list",
    "Malware": "security/Malware.list",
}


def active_rules(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def main() -> None:
    output_dir = ROOT / "providers"
    output_dir.mkdir(exist_ok=True)
    for name, relative_source in SOURCES.items():
        rules = active_rules(ROOT / "rules" / relative_source)
        content = "# Generated by scripts/build_providers.py; edit rules/ sources instead.\nbehavior: classical\npayload:\n"
        content += "".join(f"  - {rule}\n" for rule in rules)
        (output_dir / f"{name}.yaml").write_text(content, encoding="utf-8")
    print(f"Generated {len(SOURCES)} Mihomo Rule Providers.")


if __name__ == "__main__":
    main()
